# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-31 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagevideo',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepagevideo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
